#!/bin/bash


#----- verify that the results directory does not yet exist
if [ -d /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/results/bas_bias_acc-only_downsamp ]; then
  echo "WARNING : output dir /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/results/bas_bias_acc-only_downsamp already exists" >&2
  exit
fi
mkdir -p /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/results/bas_bias_acc-only_downsamp
cd /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/results/bas_bias_acc-only_downsamp


3dDeconvolve \
  -local_times -x1D_stop -allzero_OK \
  -input /data/nil-bluearc/ccp-hcp/DMCC_ALL_BACKUPS/HCP_SUBJECTS_BACKUPS/AFNI_ANALYSIS/DMCC1328342/INPUT_DATA/Stroop/baseline/lpi_scale_blur4_tfMRI_StroopBas1_AP.nii.gz /data/nil-bluearc/ccp-hcp/DMCC_ALL_BACKUPS/HCP_SUBJECTS_BACKUPS/AFNI_ANALYSIS/DMCC1328342/INPUT_DATA/Stroop/baseline/lpi_scale_blur4_tfMRI_StroopBas2_PA.nii.gz \
  -polort A -float \
  -censor /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/movregs_FD_mask.txt \
  -num_stimts 22 \
  -stim_times 1 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_purpleBLUE_acc-only.txt 'BLOCK(1,1)'  -stim_label 1 purpleBLUE \
  -stim_times 2 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_redBLUE_acc-only.txt 'BLOCK(1,1)'  -stim_label 2 redBLUE \
  -stim_times 3 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_whiteBLUE_acc-only.txt 'BLOCK(1,1)'  -stim_label 3 whiteBLUE \
  -stim_times 4 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_bluePURPLE_acc-only.txt 'BLOCK(1,1)'  -stim_label 4 bluePURPLE \
  -stim_times 5 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_redPURPLE_acc-only.txt 'BLOCK(1,1)'  -stim_label 5 redPURPLE \
  -stim_times 6 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_whitePURPLE_acc-only.txt 'BLOCK(1,1)'  -stim_label 6 whitePURPLE \
  -stim_times 7 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_blueRED_acc-only.txt 'BLOCK(1,1)'  -stim_label 7 blueRED \
  -stim_times 8 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_purpleRED_acc-only.txt 'BLOCK(1,1)'  -stim_label 8 purpleRED \
  -stim_times 9 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_whiteRED_acc-only.txt 'BLOCK(1,1)'  -stim_label 9 whiteRED \
  -stim_times 10 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_blueWHITE_acc-only.txt 'BLOCK(1,1)'  -stim_label 10 blueWHITE \
  -stim_times 11 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_purpleWHITE_acc-only.txt 'BLOCK(1,1)'  -stim_label 11 purpleWHITE \
  -stim_times 12 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_redWHITE_acc-only.txt 'BLOCK(1,1)'  -stim_label 12 redWHITE \
  -stim_times 13 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_blueBLUE_acc-only_downsamp.txt 'BLOCK(1,1)'  -stim_label 13 blueBLUE \
  -stim_times 14 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_purplePURPLE_acc-only_downsamp.txt 'BLOCK(1,1)'  -stim_label 14 purplePURPLE \
  -stim_times 15 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_redRED_acc-only_downsamp.txt 'BLOCK(1,1)'  -stim_label 15 redRED \
  -stim_times 16 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_whiteWHITE_acc-only_downsamp.txt 'BLOCK(1,1)'  -stim_label 16 whiteWHITE \
  -stim_times 17 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_pc50_i_acc-only.txt 'BLOCK(1,1)'  -stim_label 17 pc50_i \
  -stim_times 18 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_pc50_c_acc-only.txt 'BLOCK(1,1)'  -stim_label 18 pc50_c \
  -stim_times 19 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_nuisance_acc-only.txt 'BLOCK(1,1)'  -stim_label 19 nuisance \
  -stim_times 20 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_congr_modelout_acc-only.txt 'BLOCK(1,1)'  -stim_label 20 congr_modelout \
  -stim_times_AM1 21 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_sustained.txt 'dmBLOCK(1)'  -stim_label 21 sustained \
  -stim_times 22 /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/DMCC1328342_bas_transient.txt 'TENTzero(0,16.8,8)'  -stim_label 22 transient \
  -ortvec /data/nil-external/ccp/freund/stroop-rsa/glms/DMCC1328342/input/bas/motion_demean_baseline.1D movregs \
  -x1D X.xmat.1D -xjpeg X.jpg -nobucket


3dREMLfit \
  -matrix X.xmat.1D \
  -GOFORIT 5 \
  -input "/data/nil-bluearc/ccp-hcp/DMCC_ALL_BACKUPS/HCP_SUBJECTS_BACKUPS/AFNI_ANALYSIS/DMCC1328342/INPUT_DATA/Stroop/baseline/lpi_scale_blur4_tfMRI_StroopBas1_AP.nii.gz /data/nil-bluearc/ccp-hcp/DMCC_ALL_BACKUPS/HCP_SUBJECTS_BACKUPS/AFNI_ANALYSIS/DMCC1328342/INPUT_DATA/Stroop/baseline/lpi_scale_blur4_tfMRI_StroopBas2_PA.nii.gz" \
  -Rvar stats_var_DMCC1328342.nii.gz \
  -Rbuck stats_DMCC1328342.nii.gz \
  -fout -tout -nobout -verb $*


wait
echo -e "EXIT STATUS : $?"


