---
title: "robustness analysis: runwise RSA, group-level"
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
    highlight: zenburn
---



```{r setup, include = FALSE}

knitr::opts_chunk$set(
  fig.align = 'center', fig.width = 11.5, fig.fullwidth = TRUE
)

source(here::here("code", "packages.R"))
source(here("code", "strings.R"))
source(here("code", "funs.R"))
source(here("code", "plots.R"))
source(here("code", "read_atlases.R"))


d.super <- list(
  cval = read_subj_stats(glm.suffix = "fmriprep_runwise_cv-euclidean-stand_", suffix = ""),
  # glma = read_subj_stats(glm.suffix = "fmriprep_im_run_glmagg_", suffix = "") %>% rename(beta = betas),
  # crun = read_subj_stats(glm.suffix = "fmriprep_im_run_", suffix = ""),
  orig = read_subj_stats(glm.suffix = "fmriprep_", suffix = "_residual"),
  down_crun = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_", suffix = ""),
  down_both = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_both_", suffix = "")
  # down_wnrun = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_wnrun_", suffix = "")
)

# stats.subjs.wn <- 
#   data.table::fread(
#     here("out", "rsa", "stats", "subjs_pro_bias_acc-only_fmriprep_im_run_glmagg-wn_masks.csv")
#     )
# stats.subjs.wn <- stats.subjs.wn[subj %in% subjs.analysis & param %in% c("target", "distractor", "incongruency"), ]
# stats.subjs.wn %<>% dplyr::mutate(
#   roi.hemi = roi, 
#   roi = gsub("_L|_R", "", roi), 
#   hemi = ifelse(grepl("_L", roi.hemi), "L", "R")
# )
# stats.subjs.wn$beta <- (stats.subjs.wn$betas1 + stats.subjs.wn$betas2) / 2
# # stats.subjs.wn$beta <- stats.subjs.wn$betas2
# stats.subjs.wn %<>% select(-betas1, -betas2)
# 
# 
# d.super$wn <- stats.subjs.wn

theme_set(theme_bw(base_size = 14))


```


# intro


<!-- # all cors -->

```{r, echo = FALSE}

# d <- bind_rows(lapply(d.super, function(x) x[, c("subj", "roi.hemi", "param", "beta")]), .id = "type")
# 
# w <- d %>%
#   pivot_wider(names_from = "type", values_from = beta) %>%
#   group_by(roi.hemi, param)
# 
# 
# l <- split(w, interaction(w$roi.hemi, w$param))
# 
# m <- lapply(l, function(x) atanh(cor(x[sapply(x, is.numeric)])))
# mbar <- m[[1]]/length(m)
# for (ii in 2:(length(m))) {
#   mbar <- mbar + m[[ii]]/length(m)
#   
# }
# qcor(tanh(mbar))
# 
# 
# 
# r.orig.cval <- w %>%
#   select(orig, cval) %>%
#   summarize(r_orig_cval = cor(orig, cval))
# r.orig.crun <- w %>%
#   select(orig, crun) %>%
#   summarize(r_orig_crun = cor(orig, crun))
# r.orig.wn <- w %>%
#   select(orig, wn) %>%
#   summarize(r_orig_wn = cor(orig, wn))
# r.orig.glma <- w %>%
#   select(orig, glma) %>%
#   summarize(r_orig_glma = cor(orig, glma))
# # r.glma.crun <- w %>%
# #   select(glma, crun) %>%
# #   summarize(r_glma_crun = cor(glma, crun))
# r.orig.down <- w %>%
#   select(orig, down) %>%
#   summarize(r_orig_down = cor(orig, down))
# 
# 
# r <- full_join(full_join(full_join(full_join(r.orig.cval, r.orig.crun), r.orig.wn), r.orig.glma), r.orig.down)
# 
# 
# r %>%
#   reshape2::melt() %>%
#   ggplot(aes(variable, value)) +
#   geom_boxplot() +
#   facet_grid(vars(param))


```


# original (fmriprep)

```{r, echo = FALSE}
measure <- "orig"
```

`r knitr::spin_child('fpc_dissoc.R')`


# downsampled (within+cross run)

```{r, echo = FALSE}
measure <- "down_both"
```

`r knitr::spin_child('fpc_dissoc.R')`

# downsampled, cross-run

```{r, echo = FALSE}
measure <- "down_crun"
```

`r knitr::spin_child('fpc_dissoc.R')`


# cross-validated

```{r, echo = FALSE}
measure <- "cval"
```

`r knitr::spin_child('fpc_dissoc.R')`
