---
title: "modeling stroop effects (RTs) with RSA coding schemes"
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
    highlight: zenburn
---

```{r setup, include = FALSE}

## setup ----

library(here)
library(knitr)
library(magrittr)
library(dplyr)
library(data.table)
library(ggplot2)
library(mikeutils)
library(doParallel)
library(foreach)
library(gifti)
library(fANCOVA)
library(viridis)
library(colorspace)
library(boot)
library(vegan)
library(grid)
library(gridExtra)
library(lme4)
source(here("code", "strings.R"))
source(here("code", "funs.R"))
source(here("code", "read_atlases.R"))


## global settings


theme_set(theme_bw(base_size = 12))
n_cores <- detectCores()
nreps <- 5E3
nresamps <- 1E4

## strings


colors.model <- c(incongruency = "#d95f02", target = "#1b9e77", distractor = "#7570b3")

md <- list(
  core       = c("p9-46v", "a9-46v", "i6-8", "AVI", "8C", "IFJp", "IP2", "IP1", "PFm", "8BM", "SCEF"),
  extended   = c(
    "p9-46v", "a9-46v", "i6-8", "AVi", "8C", "IFJp", "IP2", "IP1", "PFm", "8BM",
    "TE1m", "TE1p", "PGs", "PFm", "AIP", "MIP", "LIPd", "IP1", "IP2", "s6-8", 
    "i6-8", "a9-46v", "FOP5", "AVI", "11l", "a10p", "p10p", "a47r", "p47r"
  )
)

params.interest <- c("target", "distractor", "incongruency")
colors.profs <- c(
  incon = "#d95f02ff", targt = "#1b9e77ff", distr = "#7570b3ff", targt.incon = "#26190dff", targt.distr = "#4682b4ff"
)

## data

stats.subjs.superparcels <- 
  fread(
    here("out", "rsa", "stats", paste0("subjs_pro_bias_acc-only_masks_pearson_residual_glm-tdic.csv"))
    ) %>%
    filter(grepl("^anat_|vwfa", .$roi), is.analysis.group) %>%
    mutate(roi = gsub("anat_", "", .$roi))

stats.subjs.tdic <- fread(
  here("out", "rsa", "stats", paste0("subjs_pro_bias_acc-only_mmp_pearson_residual_glm-tdic.csv"))
)
stats.subjs.tdic <- stats.subjs.tdic[is.analysis.group == TRUE & y == "rank", ]  ## EXCLUDE HELD OUT SUBJECTS!
stats.subjs.tdic <- stats.subjs.tdic[, "coef" := NULL]
stats.subjs.tdic %<>% full_join(atlas.key$mmp, by = "roi")


stats.group.tdic <- fread(here("out", "rsa", "stats", "group_pro_bias_acc-only_mmp_pearson_residual_glm-tdic.csv"))
stats.group.tdic <- stats.group.tdic[measure == "beta" & y == "rank" & param %in% params.interest, ]
stats.group.tdic <- stats.group.tdic[, c("measure", "y") := NULL]

## underlay images

hcp <- list(
  L  = readGIfTI(
    file.path(dir.atlas, "surf", "HCP_S1200_GroupAvg_v1", "S1200.L.very_inflated_MSMAll.32k_fs_LR.surf.gii")
  ),
  R = readGIfTI(
    file.path(dir.atlas, "surf", "HCP_S1200_GroupAvg_v1", "S1200.R.very_inflated_MSMAll.32k_fs_LR.surf.gii")
  )
)

## MMP template for defining masks

mmp <- list(
  L = read_gifti2matrix(file.path(dir.atlas, "MMP_surface", "mmpL.func.gii")) %>% c,
  R = read_gifti2matrix(file.path(dir.atlas, "MMP_surface", "mmpR.func.gii")) %>% c
)

mmp$L[mmp$L > 0] <- mmp$L[mmp$L > 0] - 180
mmp$R[mmp$R > 0] <- mmp$R[mmp$R > 0] + 180

## get 'coding' ROIs ----

rois.targt <- stats.group.tdic[param == "target" & p.fdr < 0.05, roi]
rois.distr <- stats.group.tdic[param == "distractor" & p.fdr < 0.05, roi]
rois.incon <- stats.group.tdic[param == "incongruency" & p.fdr < 0.05, roi]
rois.congr <- stats.group.tdic[param == "congruency" & p.fdr < 0.05, roi]

keep.these.bois <- c("m", "v", "p.fdr", "num.roi", "roi", "hemi")
stats.coding.targt <- stats.group.tdic[param == "target", ..keep.these.bois]
stats.coding.distr <- stats.group.tdic[param == "distractor", ..keep.these.bois]
stats.coding.incon <- stats.group.tdic[param == "incongruency", ..keep.these.bois]
stats.coding.congr <- stats.group.tdic[param == "congruency", ..keep.these.bois]

## intersections

rois.targt.incon <- intersect(rois.targt, rois.incon)
rois.targt.distr <- intersect(rois.targt, rois.distr)
rois.distr.incon <- intersect(rois.distr, rois.incon)  ## none
rois.targt.distr.incon <- Reduce(intersect, list(rois.targt, rois.incon, rois.distr))  ## none


```

# one-sample (against zero) results

```{r}

rois.targt

rois.distr

rois.incon

rois.congr

rois.targt.incon

rois.targt.distr

rois.distr.incon

rois.targt.distr.incon

```

# pairwise comparison: target > distractor

```{r}

## get p values

targt.vs.distr <-
  
  stats.subjs.tdic %>%
  
  filter(param %in% c("target", "distractor"), roi %in% rois.targt) %>%
  mutate(param = factor(param, levels = c("target", "distractor"))) %>%
  
  group_by(roi) %>%
  summarize(
    p = wilcox.test(beta ~ param)$p.value,
    b = mean(beta[param == "target"]) - mean(beta[param == "distractor"])
  ) %>%
  
  mutate(p.fdr = p.adjust(p, method = "fdr"))

targt.vs.distr %<>% left_join(atlas.key$mmp, by = "roi")

targt.vs.distr %>% arrange(community, -p.fdr) %>% filter(p.fdr < 0.05) %>% kable(digits = 2)

```

# test for dissociation

```{r}

rois.medial <- targt.vs.distr %>% 
  filter(community.short == "aCC and mPFC", p.fdr < 0.05) %>% 
  pull("roi")
rois.lateral <- targt.vs.distr %>% 
  filter(community.short %in% c("dlPFC", "PM"), p.fdr < 0.05) %>% 
  pull("roi")
rois.lppc <- targt.vs.distr %>% 
  filter(community.short %in% c("iP", "sP"), p.fdr < 0.05) %>% 
  pull("roi")

d <- stats.subjs.tdic %>% 
  
  filter(roi %in% c(rois.lateral, rois.medial, rois.lppc)) %>%
  
  mutate(
    region = ifelse(
      roi %in% rois.lateral, "LFC", 
      ifelse(
        roi %in% rois.medial, "MFC",
        ifelse(roi %in% rois.lppc, "LPPC", NA)
        )
      )
    )

fit.lm.t <- lmer(
  beta ~ region + (1 | subj), 
  d %>% filter(region %in% c("LFC", "MFC"), param == "target")
  )
summary(fit.lm.t)

fit.lm.c <- lmer(
  beta ~ region + (1 | subj), 
  d %>% filter(region %in% c("LFC", "MFC"), param == "incongruency")
  )
summary(fit.lm.c)


## within region test:

fit.mfc <- lmer(
  beta ~ param + roi + (1 | subj), 
  d %>% filter(region == "MFC", param %in% c("target", "incongruency"))
  )
summary(fit.mfc)



d %>%  
  
  filter(param %in% c("incongruency", "target")) %>%
  
  ggplot(aes(region, beta, color = param)) +
  
  stat_summary(fun.data = mean_cl_boot, position = position_dodge(width = 0.5), size = 2) +
  
  geom_point(position = position_jitterdodge(dodge.width = 0.5, jitter.width = 0.25)) +
  
  facet_wrap(vars(roi))

d %>%  
  
  filter(param %in% c("incongruency", "target")) %>%
  
  ggplot(aes(param, beta, color = param)) +
  
  stat_summary(fun.data = mean_cl_boot, size = 2) +
  
  # geom_point(position = position_jitterdodge(dodge.width = 0.5, jitter.width = 0.25)) +
  
  facet_grid(vars(region), vars(roi), scale = "free_x") +

  scale_color_manual(values = colors.model)

```

# superparcels

```{r}


stats.group.superparcels <- stats.subjs.superparcels %>%
  
  group_by(param, roi) %>%
  summarize(
    p = wilcox.test(beta, alternative = "greater")$p.value,
    b = mean(beta)
    # b = mean(beta[param == "target"]) - mean(beta[param == "distractor"])
  ) %>%
  
  group_by(param) %>%
  mutate(p.fdr = p.adjust(p, method = "fdr"))

superparcels.target <- stats.group.superparcels %>% filter(p.fdr < 0.05, param == "target") %>% pull(roi)



superparcels.targt.vs.distr <- stats.subjs.superparcels %>%
  
  filter(param %in% c("target", "distractor"), roi %in% superparcels.target) %>%
  mutate(param = factor(param, levels = c("target", "distractor"))) %>%
  
  group_by(roi) %>%
  summarize(
    p = wilcox.test(beta ~ param)$p.value,
    b = mean(beta[param == "target"]) - mean(beta[param == "distractor"])
  ) %>%
  
  mutate(p.fdr = p.adjust(p, method = "fdr"))

superparcels.targt.pref <- superparcels.targt.vs.distr %>% filter(p.fdr < 0.05) %>% pull(roi)

superparcels.targt.vs.distr %>% arrange(-p.fdr) %>% filter(p.fdr < 0.05)



stats.subjs.superparcels %>%
  
  filter(param %in% params.interest) %>%
  
  ggplot(aes(param, beta, color = param)) +
  stat_summary(fun.data = mean_cl_boot, position = position_dodge(width = 0.5), size = 1) +
  facet_wrap(vars(roi)) +
  
  scale_color_manual(values = colors.model)

```

