---
  title: "targeted analysis of left lateral occipitotemporal cortex ('vwfa')"
  output: html_document
---


```{r setup}

library(here)
library(magrittr)
library(dplyr)
library(data.table)
library(ggplot2)
library(mikeutils)
library(doParallel)
library(foreach)
source(here("code", "strings.R"))
source(here("code", "read_atlases.R"))
source(here("code", "read_masks.R"))

```

```{r}

stats.subjs.tdic <- fread(
  here("out", "rsa", "stats", paste0("subjs_pro_bias_acc-only_masks_pearson_residual_glm-tdic.csv"))
  )

stats.group.tdic <- stats.subjs.tdic %>%
  group_by(roi, model, param, y) %>%
  summarize(
    v    = wilcox.test(beta, alternative = "greater")$statistic,
    p    = wilcox.test(beta, alternative = "greater")$p.value,
    beta = tanh(mean(atanh(beta))),  ## must be last in this summarize()
  )

stats.group.tdic

## which MMP ROIs are closest?
overlap <- numeric(180)
for (roi.i in seq_len(180)) {
  mask.i <- as.numeric(atlas$mmp == roi.i)
  overlap[roi.i] <- mask.i %*% c(masks$vwfa)
}


mmp.left <- atlas.key$mmp %>% filter(hemi == "L")
mmp.left$overlap.vwfa <- overlap

mmp.left %>% arrange(-overlap.vwfa) %>% filter(overlap.vwfa > 0)

```

