---
title: "exploratory, whole-cortex RSA: master report"
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
    highlight: zenburn
---


```{r setup, include = FALSE}

knitr::opts_chunk$set(
  fig.align = 'center', fig.width = 11.5, fig.fullwidth = TRUE
)

source(here::here("code", "packages.R"))
source(here("code", "strings.R"))
source(here("code", "funs.R"))
source(here("code", "plots.R"))
source(here("code", "read_atlases.R"))

stats.subjs.mmp <- read_subj_stats(roi.set = "mmp")

```


# run stats

```{r get-stats}

stats.group.mmp <- stats.subjs.mmp %>%
  
  group_by(param, roi) %>%
  
  summarize(
    v = wilcox.test(beta, alternative = "greater")$statistic,
    p = wilcox.test(beta, alternative = "greater")$p.value,
    b = mean(beta),
    .groups = "drop_last"
  ) %>%
  
  mutate(p.fdr = p.adjust(p, method = "fdr"))

stats.group.mmp %<>% full_join(atlas.key$mmp, by = "roi")
stats.group.mmp <- as.data.table(stats.group.mmp)

(rois.targt <- stats.group.mmp[param == "target" & p.fdr < 0.05, roi])
(rois.distr <- stats.group.mmp[param == "distractor" & p.fdr < 0.01, roi])
(rois.incon <- stats.group.mmp[param == "incongruency" & p.fdr < 0.05, roi])

## intersections

(rois.targt.incon <- intersect(rois.targt, rois.incon))
(rois.targt.distr <- intersect(rois.targt, rois.distr))
(rois.distr.incon <- intersect(rois.distr, rois.incon))
(rois.targt.distr.incon <- Reduce(intersect, list(rois.targt, rois.incon, rois.distr)))

```


# make overlays for workbench

```{r workbench-figs}
## read or write files for workbench ----

fname.overlay.coding <- c(
  here("out", "explor", "target.png"), 
  here("out", "explor", "distractor.png"),
  here("out", "explor", "incongruency.png")
)

if (all(file.exists(fname.overlay.coding))) {
  
  p.coding <- lapply(fname.overlay.coding, image_read)
  grobs <- lapply(p.coding, rasterGrob)
  
  grid.arrange(
    arrangeGrob(grobs[[1]], top = textGrob("target", gp = gpar(fontsize = 24))), 
    arrangeGrob(grobs[[2]], top = textGrob("distractor", gp = gpar(fontsize = 24))),
    arrangeGrob(grobs[[3]], top = textGrob("incongruency", gp = gpar(fontsize = 24))),
    ncol = 3
  )
  
} else {
  
  overlay.targt <- stats.group.mmp %>% 
    
    filter(param == "target") %>% dplyr::select(roi, num.roi, hemi, v, p.fdr, b) %>% 
    mutate(val = ifelse(p.fdr < 0.05, v, 0)) %>%
    arrange(num.roi)
  
  cifti.convert(
    fname.overlay  = "group_target",
    dir.to.write   = here("out", "explor"),
    values.overlay = overlay.targt$val,
    dir.template   = here("out", "wb"),
    name.atlas     = "glasser"
  )
  
  overlay.distr <- stats.group.mmp %>% 
    
    filter(param == "distractor") %>% select(roi, num.roi, hemi, v, p.fdr, b) %>% 
    mutate(val = ifelse(p.fdr < 0.05, v, 0)) %>%
    arrange(num.roi)
  
  cifti.convert(
    fname.overlay  = "group_distractor",
    dir.to.write   = here("out", "explor"),
    values.overlay = overlay.distr$val,
    dir.template   = here("out", "wb"),
    name.atlas     = "glasser"
  )
  
  overlay.incon <- stats.group.mmp %>% 
    
    filter(param == "incongruency") %>% select(roi, num.roi, hemi, v, p.fdr, b) %>%
    mutate(val = ifelse(p.fdr < 0.05, v, 0)) %>%
    arrange(num.roi)
  
  cifti.convert(
    fname.overlay  = "group_incongruency",
    dir.to.write   = here("out", "explor"),
    values.overlay = overlay.incon$val,
    dir.template   = here("out", "wb"),
    name.atlas     = "glasser"
  )
  
  ## now build and save plots with workbench, and re-run this .rmd file
  
}
```


# top 10% of target coding parcels

```{r top-target}

rois.top.targt <- stats.group.mmp %>% filter(param == "target", roi %in% rois.targt) %>% slice_max(v, prop = 0.1) %>% pull(roi)

means.top.target <- stats.subjs.mmp %>%
  
  filter(roi %in% rois.top.targt, param %in% "target") %>%
  group_by(roi, community) %>%
  summarize(res = list(boot_mean_ci(beta))) %>% 
  
  tidyr::unnest(cols = c(res))


p.top.target <- 
  
  means.top.target %>%  
  
  ungroup %>%
  mutate(roi = factor(roi, levels = roi[order(y)])) %>%
  
  ggplot(aes(roi, y, color = community)) +
  geom_point(size = geom.point.size) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0, size = geom.line.size) +
  # coord_capped_cart(left = "both") +
  labs(y = bquote("Target model fit ("*bar(beta)*")"), x = "Parcel") +
  scale_color_brewer(type = "qual", palette = 3) +
  scale_y_continuous(limits = c(0, 0.12), breaks = c(0, 0.05, 0.1), position = "right") +
  coord_flip() +
  coord_capped_flip(top = "both", left = "both") +
  theme(
    # legend.position = "none", 
    panel.grid      = element_blank(), 
    panel.border    = element_blank(),
    axis.line     = element_line(size = axis.line.size),
    axis.text       = element_text(size = axis.text.size*3/4),
    # axis.text.x     = element_text(color = colors.model),
    axis.ticks.x    = element_line(size = axis.line.size),
    # axis.ticks.x    = element_blank(),
    axis.title      = element_text(size = axis.title.size),
    # axis.text.y = element_text(angle = 90, vjust = 0, hjust = 1)
  )

p.top.target

ggsave(here("out", "explor", "top_target.pdf"), p.top.target, device = "pdf", width = 5, height = 3)

```


# write tables

```{r tables}
## table ----

table.group.mmp <- stats.group.mmp %>% select(param, roi, "$\\bar\\beta$" = b, v, p = p.fdr, network, md)
table.group.mmp$md[table.group.mmp$md == "none"] <- ""
table.group.mmp$md[table.group.mmp$md == "extended"] <- "penumbra"
table.group.mmp$parcel <- gsub("_", "\\\\textunderscore ", table.group.mmp$roi)
table.group.mmp <- as.data.frame(table.group.mmp)
table.group.mmp <- table.group.mmp[
  c(
    names(table.group.mmp)[length(names(table.group.mmp))],
    names(table.group.mmp)[1:(length(names(table.group.mmp))-1)]
  )
]

table.group.mmp.distr <- table.group.mmp %>% filter(param == "distractor", roi %in% rois.distr) %>% select(-param, -roi) %>% arrange(-v)
table.group.mmp.incon <- table.group.mmp %>% filter(param == "incongruency", roi %in% rois.incon) %>% select(-param, -roi) %>% arrange(-v)
table.group.mmp.targt <- table.group.mmp %>% filter(param == "target", roi %in% rois.targt) %>% select(-param, -roi) %>% arrange(-v)

fwrite(table.group.mmp.distr, here("out", "explor", "table_distractor.csv"), quote = TRUE)
fwrite(table.group.mmp.incon, here("out", "explor", "table_incongruency.csv"), quote = TRUE)
fwrite(table.group.mmp.targt, here("out", "explor", "table_target.csv"), quote = TRUE)

```

# proportions of network assignments per model

```{r piechart}

stats.group.mmp %>%
  
  filter(p.fdr < 0.05) %>%
  
  ggplot(aes(param, fill = network)) +
  geom_bar()

proportions <- bind_rows(
  distr  = atlas.key$mmp %>% filter(roi %in% rois.distr) %>% group_by(network) %>% summarize(prop = n() / length(rois.distr)),
  incon  = atlas.key$mmp %>% filter(roi %in% rois.incon) %>% group_by(network) %>% summarize(prop = n() / length(rois.incon)),
  target = atlas.key$mmp %>% filter(roi %in% rois.targt) %>% group_by(network) %>% summarize(prop = n() / length(rois.targt)),
  all    = atlas.key$mmp %>% group_by(network) %>% summarize(prop = n() / nrow(atlas.key$mmp)),
  .id = "model"
)

proportions %>%
  
  ggplot(aes(x = "", y = prop, fill = network)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  
  facet_grid(cols = vars(model))

```

