---
title: "microphone comparisions"
author: "michael freund"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}

library(mikeutils)
library(magrittr)
library(here)
library(knitr)
library(dplyr)
library(data.table)
library(ggplot2)
library(grid)
library(gridExtra)
library(colorspace)
library(viridis)
library(nlme)
library(lme4)
library(multcomp)

## opts ----

opts_chunk$set(
  cache = TRUE, fig.align = "center", echo = TRUE, dev = "pdf"
)
theme_set(theme_bw(base_size = 12))

## data ----

stroop <- read.csv(here("data", "behavior-and-events_group201902.csv"),  stringsAsFactors = FALSE)
stroop %<>%
  arrange(subj, session, run, trial.num) %>%
  group_by(subj, session, run) %>%
  mutate(
    error         = 1 - acc,
    post.error    = lag(error),
    n1.trial.type = lag(trial.type),
    n2.trial.type = lag(n1.trial.type)
    )
subj.summary <- read.csv(here("data", "summary_group201902.csv"), stringsAsFactors = FALSE) %>% 
  filter(task == "stp", subj %in% unique(stroop$subj))


dates1 <- read.csv(here("data", "dates.csv"), stringsAsFactors = FALSE)
dates2 <- read.csv(here("data", "dates_missing_from-gcal.csv"), stringsAsFactors = FALSE)

dates1[c("BAS.day", "PRO.day", "REA.day")] <- lapply(dates1[c("BAS.day", "PRO.day", "REA.day")], as.Date)
dates2[c("session1", "session2", "session3")] <- lapply(dates2[c("session1", "session2", "session3")], as.Date)

## vars ----

color.congruency <- c("incon" = "#b2182b", "congr" = "#2166ac")

```

## microphone differences?

```{r wrangle_dates}

## subject & microphone list ----

## fomri arrive (range):
fomri.arrive.lb <- "2018-05-01"
fomri.arrive.ub <- "2018-05-31"

## definite fomri
fomri.switch <- "2018-06-28"
## exceptions:
##  DMCC515268_baseline DMCC3 (June 30th, 2018) and DMCC6904377_reactive DMCC2 (July 1st, 2018)

dates1.is.microoptics <- dates1[c("BAS.day", "PRO.day", "REA.day")] < fomri.arrive.lb
dates1.is.fomri <- dates1[c("BAS.day", "PRO.day", "REA.day")] > fomri.switch

all(dates1.is.microoptics, na.rm = TRUE)  ## all microoptics

dates2.is.microoptics <- dates2[c("session1", "session2", "session3")] < fomri.arrive.lb
dates2.is.fomri <- dates2[c("session1", "session2", "session3")] > fomri.switch

dates2$all.microoptics <- apply(dates2.is.microoptics, 1, function(x) all(x))
dates2$all.fomri <- apply(dates2.is.fomri, 1, function(x) all(x))

subj.microoptics <- dates2 %>% filter(all.microoptics & subj != "DMCC6904377") %>% .$subj
subj.microoptics <- union(subj.microoptics, dates1$subj)
subj.fomri <- dates2 %>% filter(all.fomri & subj != "DMCC6904377") %>% .$subj


stroop$mic <- ifelse(
  stroop$subj %in% subj.fomri,
  "fomri",
  ifelse(
    stroop$subj %in% subj.microoptics, 
    "micro",
    "unknown"
  )
)

table(stroop$subj, stroop$mic)
```


```{r rawvals_all, fig.height = 15, fig.width = 20}

stroop %>%
  ggplot(aes(subj, rt, color = mic)) +
  facet_grid(vars(session)) +
  geom_point(position = position_jitter(width = 0.1), size = 0.5, alpha = 0.3) +
  geom_boxplot(position = position_nudge(1/3), notch = TRUE, width = 0.2) +
  scale_color_brewer(type = "qual", palette = 2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0))

```

```{r rawvals}

stroop %>%
  group_by(mic, subj) %>%
  summarize(freq = sum(rt == 0, na.rm = TRUE)) %>%
  ggplot(aes(mic, freq)) +
  geom_point(size = 2) +
  labs(y = "frequency of rt == 0 per subj")

stroop %>%
  group_by(mic, subj, error) %>%
  summarize(freq = sum(error, na.rm = TRUE)) %>%
  ggplot(aes(mic, freq)) +
  geom_point(size = 2, position = position_jitter(width = 0.1), alpha = 0.4) +
  labs(y = "frequency of errors per subj")

stroop %>%
  group_by(mic, subj, acc.final) %>%
  summarize(freq = n()) %>%
  ggplot(aes(mic, freq)) +
  facet_grid(cols = vars(acc.final)) +
  geom_point(size = 2, position = position_jitter(width = 0.1), alpha = 0.4) +
  labs(y = "frequency of acc.final codings per subj")

```


```{r qq, fig.height = 15, fig.width = 20}

stroop %>%
  ggplot(aes(sample = rt, color = mic)) +
  stat_qq(alpha = 0.3, size = 0.15) +
  stat_qq_line(size = 0.25) +
  facet_wrap(vars(subj)) +
  scale_color_brewer(type = "qual", palette = 2)

```


```{r prelim_look}

stroop.mean.sd <- stroop %>%
  group_by(mic, subj, session) %>%
  summarize(rt.mean = mean(rt, na.rm = TRUE), rt.sd = sd(rt, na.rm = TRUE))

grid.arrange(
  stroop.mean.sd %>%
    ggplot(aes(mic, rt.mean)) +
    facet_grid(vars(session)) +
    geom_point(position = position_jitter(width = 0.1)) +
    geom_boxplot(position = position_nudge(1/3), notch = FALSE, width = 0.2),
  stroop.mean.sd %>%
    ggplot(aes(mic, rt.sd)) +
    facet_grid(vars(session)) +
    geom_point(position = position_jitter(width = 0.1)) +
    geom_boxplot(position = position_nudge(1/3), notch = FALSE, width = 0.2)
)

```

## model

### differences in mean stroop effect btw mics?

```{r means}

stroop.rt <- stroop %>% filter(!is.na(rt), rt > 200, acc == 1)

# g <- paste0(stroop.rt$subj, "_", stroop.rt$session)
# l <- split(stroop.rt, g)
# 
# fits <- lapply(l, function(d) lm(rt ~ trial.type, d))
# stroop.rt$resids <- unlist(lapply(fits, resid), use.names = FALSE)
# bs <- do.call(rbind, lapply(fits, coef))
# bs <- cbind(bs, reshape2::colsplit(rownames(bs), "_", c("subj", "session"))

stroop.rt %<>%
  mutate(
    bas   = as.numeric(session == "bas"),
    pro   = as.numeric(session == "pro"),
    rea   = as.numeric(session == "rea"),
    congr = as.numeric(trial.type == "c"),
    incon = as.numeric(trial.type == "i"),
    micro = as.numeric(mic == "micro"),
    fomri = as.numeric(mic == "fomri")
  )

fit.noint <- lmer(
  rt ~ 
    0 +
    congr:bas:micro + congr:pro:micro + congr:rea:micro +
    incon:bas:micro + incon:pro:micro + incon:rea:micro +
    congr:bas:fomri + congr:pro:fomri + congr:rea:fomri +
    incon:bas:fomri + incon:pro:fomri + incon:rea:fomri +
    (
    0 + 
    congr:bas + congr:pro + congr:rea +
    incon:bas + incon:pro + incon:rea
    | subj
    ),
  stroop.rt,
  subset = mic != "unknown",
  control = lmerControl(optimizer = "bobyqa")
  )

# fits.noint <- allFit(fit.noint)
# summary(fits.noint)
# fit.noint <- fits.noint$bobyqa

summary(fit.noint)

bnames <- rownames(coef(summary(fit.noint)))

m <- data.frame(
  bas   = grepl("bas", bnames),
  pro   = grepl("pro", bnames),
  rea   = grepl("rea", bnames),
  congr = grepl("congr", bnames),
  incon = grepl("incon", bnames),
  fomri = grepl("fomri", bnames),
  micro = grepl("micro", bnames)
)

rownames(m) <- bnames
contrast <- rbind(
  "fomri-micro|bas" = (m$fomri - m$micro) * m$bas / 2,
  "fomri-micro|pro" = (m$fomri - m$micro) * m$pro / 2,
  "fomri-micro|rea" = (m$fomri - m$micro) * m$rea / 2,
  "stroop:(fomri-micro)|bas" = (m$incon - m$congr) * (m$fomri - m$micro) * m$bas / 2,
  "stroop:(fomri-micro)|pro" = (m$incon - m$congr) * (m$fomri - m$micro) * m$pro / 2,
  "stroop:(fomri-micro)|rea" = (m$incon - m$congr) * (m$fomri - m$micro) * m$rea / 2
)
colnames(contrast) <- bnames

results <- glht(fit.noint, contrast, alternative = "two.sided")
summary(results, adjusted(type = "none"))

```

Summary

* fomri microphone recorded faster RTs
* no observed impact of microphone on size of mean stroop effect

## differences in variance btw microphones?

```{r}

cl1 <- lmeControl(
 maxIter = 100000, msMaxIter = 100000, niterEM = 100000,
 msMaxEval = 100000, tolerance = 0.000001, msTol = 0.0000001, returnObject = TRUE,
 minAbsParApVar = 0.05, opt = c("nlminb"), optimMethod = "BFGS"
 )

## proactive

m.hom.pro <- lme(
  rt ~ trial.type * mic, 
  random = ~ 1 | subj,
  data = stroop.rt %>% filter(mic != "unknown"), 
  subset = session == "pro",
  control = cl1
  )

m.het.mic.pro <- update(m.hom.pro, . ~ ., weights = varIdent(form = ∼ 1 | mic))
m.het.subj.pro <- update(m.hom.pro, . ~ ., weights = varIdent(form = ∼ 1 | subj))

summary(m.hom.pro)
summary(m.het.mic.pro)
summary(m.het.subj.pro)

anova(m.hom.pro, m.het.mic.pro, m.het.subj.pro)

## baseline

m.hom.bas <- lme(
  rt ~ trial.type * mic, 
  random = ~ 1 | subj,
  data = stroop.rt %>% filter(mic != "unknown"), 
  subset = session == "bas",
  control = cl1
  )

m.het.mic.bas <- update(m.hom.bas, . ~ ., weights = varIdent(form = ∼ 1 | mic))
m.het.subj.bas <- update(m.hom.bas, . ~ ., weights = varIdent(form = ∼ 1 | subj))

summary(m.hom.bas)
summary(m.het.mic.bas)
summary(m.het.subj.bas)

anova(m.hom.bas, m.het.mic.bas, m.het.subj.bas)

## reactive

m.hom.rea <- lme(
  rt ~ trial.type * mic, 
  random = ~ 1 | subj,
  data = stroop.rt %>% filter(mic != "unknown"), 
  subset = session == "rea",
  control = cl1
  )

m.het.mic.rea <- update(m.hom.rea, . ~ ., weights = varIdent(form = ∼ 1 | mic))
m.het.subj.rea <- update(m.hom.rea, . ~ ., weights = varIdent(form = ∼ 1 | subj))

summary(m.hom.rea)
summary(m.het.mic.rea)
summary(m.het.subj.rea)

anova(m.hom.rea, m.het.mic.rea, m.het.subj.rea)

```

```{r}

plot(m.hom.pro)
plot(m.het.subj.pro)

d <- filter(stroop.rt, mic != "unknown", session == "pro")

plot(as.factor(d$trial.num), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$run), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$trial.type), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$color), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$word), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$item), resid(m.het.subj.pro, type = "pearson"))

plot(interaction(d$pc, d$trial.type), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$iti), resid(m.het.subj.pro, type = "pearson"))

plot(as.factor(d$mic), resid(m.het.subj.pro, type = "pearson"))


plot(interaction(d$mic, d$trial.type, d$pc), resid(m.het.subj.pro, type = "pearson"))


plot(
  fitted(m.het.subj.pro), resid(m.het.subj.pro),
  col = ifelse(d$mic == "micro", "black", ifelse(d$mic == "fomri", "firebrick", "grey50")),
  pch = 16
  )

plot(
  fitted(m.het.subj.pro), resid(m.het.subj.pro, type = "pearson"),
  col = ifelse(d$mic == "micro", "black", ifelse(d$mic == "fomri", "firebrick", "grey50")),
  pch = 16
  )

```

```{r}
m.het.subj.trial.type.pro <- update(m.hom.pro, . ~ ., weights = varIdent(form = ∼ trial.type | subj))

summary(m.het.subj.trial.type.pro)
anova(m.het.subj.trial.type.pro, m.het.subj.pro)
```



