---
title: "robustness analysis: runwise RSA, group-level"
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
    highlight: zenburn
---



```{r setup, include = FALSE}

knitr::opts_chunk$set(
  fig.align = 'center', fig.width = 11.5, fig.fullwidth = TRUE
)

source(here::here("code", "packages.R"))
source(here("code", "strings.R"))
source(here("code", "funs.R"))
source(here("code", "plots.R"))
source(here("code", "read_atlases.R"))


d.super <- list(
  cval = read_subj_stats(glm.suffix = "fmriprep_runwise_cv-euclidean-stand_", suffix = ""),
  # glma = read_subj_stats(glm.suffix = "fmriprep_im_run_glmagg_", suffix = "") %>% rename(beta = betas),
  # crun = read_subj_stats(glm.suffix = "fmriprep_im_run_", suffix = ""),
  orig = read_subj_stats(glm.suffix = "fmriprep_", suffix = "_residual"),
  down_crun = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_crun_", suffix = ""),
  down_both = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_both_", suffix = "")
  # down_wnrun = read_subj_stats(glm.suffix = "fmriprep_im_run_downsampled_wnrun_", suffix = "")
)

# stats.subjs.wn <- 
#   data.table::fread(
#     here("out", "rsa", "stats", "subjs_pro_bias_acc-only_fmriprep_im_run_glmagg-wn_masks.csv")
#     )
# stats.subjs.wn <- stats.subjs.wn[subj %in% subjs.analysis & param %in% c("target", "distractor", "incongruency"), ]
# stats.subjs.wn %<>% dplyr::mutate(
#   roi.hemi = roi, 
#   roi = gsub("_L|_R", "", roi), 
#   hemi = ifelse(grepl("_L", roi.hemi), "L", "R")
# )
# stats.subjs.wn$beta <- (stats.subjs.wn$betas1 + stats.subjs.wn$betas2) / 2
# # stats.subjs.wn$beta <- stats.subjs.wn$betas2
# stats.subjs.wn %<>% select(-betas1, -betas2)
# 
# 
# d.super$wn <- stats.subjs.wn

theme_set(theme_bw(base_size = 14))


```


# intro


<!-- ## testing sensitivity of effects with strong priors to across-run estimation -->

```{r, echo = FALSE}

# d <- rbindlist(d.super, idcol = "method")
# 
# dat_text <- data.frame(
#   param = c("target", "distractor"),
#   roi = c("smmouth", "V1"),
#   x = c(2, 2),
#   y = c(6, 5.2)
# )
# 
# d %>%
#   
#   filter(
#     method %in% c("down_both", "down_crun"),
#     (roi == "smmouth" & param == "target") | (roi == "V1" & param == "distractor")
#     ) %>% 
#   group_by(method, roi, param) %>%
#   summarize(tstat = t.test(beta)$statistic)

  # mutate(method = ordered(method, levels = c("down_both", "down_crun"))) %>%
  # 
  # ggplot(aes(factor(method), tstat, group = param)) +
  # geom_point(aes(color = param), size = 4) +
  # geom_line(aes(color = param), size = 3) +
  # 
  # scale_color_manual(values = colors.model) +
  # 
  # facet_grid(cols = vars(roi)) +
  # geom_text(data = dat_text, aes(x = x, y = y, label = param, color = param), size = 7, hjust = 1, fontface = "bold") +
  # 
  # scale_x_discrete(labels = c("within-run\ncorrelation", "cross-run\ncorrelation")) +
  # scale_y_continuous(limits = c(0, 8)) +
  # labs(x = "RSA type", y = "t statisic") +
  # theme(legend.position = "none")


# d <- bind_rows(lapply(d.super, function(x) x[, c("subj", "roi.hemi", "param", "beta")]), .id = "type")
# 
# w <- d %>%
#   pivot_wider(names_from = "type", values_from = beta) %>%
#   group_by(roi.hemi, param)
# 
# 
# l <- split(w, interaction(w$roi.hemi, w$param))
# 
# m <- lapply(l, function(x) atanh(cor(x[sapply(x, is.numeric)])))
# mbar <- m[[1]]/length(m)
# for (ii in 2:(length(m))) {
#   mbar <- mbar + m[[ii]]/length(m)
#   
# }
# qcor(tanh(mbar))
# 
# 
# 
# r.orig.cval <- w %>%
#   select(orig, cval) %>%
#   summarize(r_orig_cval = cor(orig, cval))
# r.orig.crun <- w %>%
#   select(orig, crun) %>%
#   summarize(r_orig_crun = cor(orig, crun))
# r.orig.wn <- w %>%
#   select(orig, wn) %>%
#   summarize(r_orig_wn = cor(orig, wn))
# r.orig.glma <- w %>%
#   select(orig, glma) %>%
#   summarize(r_orig_glma = cor(orig, glma))
# # r.glma.crun <- w %>%
# #   select(glma, crun) %>%
# #   summarize(r_glma_crun = cor(glma, crun))
# r.orig.down <- w %>%
#   select(orig, down) %>%
#   summarize(r_orig_down = cor(orig, down))
# 
# 
# r <- full_join(full_join(full_join(full_join(r.orig.cval, r.orig.crun), r.orig.wn), r.orig.glma), r.orig.down)
# 
# 
# r %>%
#   reshape2::melt() %>%
#   ggplot(aes(variable, value)) +
#   geom_boxplot() +
#   facet_grid(vars(param))


```


# a common plot

```{r, fig.height = 10}


d <- rbindlist(d.super, idcol = "method")

dat_text <- data.frame(
  param = c("incongruency", "target", "distractor"),
  hemi = "L",
  roi = "dlpfc",
  x = 2.5,
  y = c(0.11, 0.09, 0.07)
)


d %>%
  
  filter(
    method %in% c("down_both", "down_crun", "cval"),
    roi %in% c("dlpfc", "dmfc", "lppc")
    ) %>%

  mutate(method = ordered(method, levels = c("down_both", "down_crun", "cval"))) %>%
  
  ggplot(aes(method, beta, color = param)) +
  facet_grid(vars(roi), vars(hemi), scales = "free") +

  geom_hline(yintercept = 0) +
  
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = 0.25), size = 1) +
  geom_line(
    data = . %>% 
      group_by(method, roi, param, hemi) %>%
      summarize(beta = mean(beta)),
    aes(group = param), position = position_dodge(width = 0.25),
    size = 2
  ) +
  
  geom_text(data = dat_text, aes(x = x, y = y, label = param), hjust = 0, fontface = "bold", size = 6) +
  scale_color_manual(values = colors.model) +
  
  scale_x_discrete(
    labels = c("within-run\ndownsample", "cross-run\ndownsample", "cross-validated")
    ) +
  
  theme(legend.position = "none") +
  
  labs(x = "RSA method", y = "RSA model fit ()")
  



```


# original (fmriprep)

```{r, echo = FALSE}
measure <- "orig"
```

`r knitr::spin_child('fpc_dissoc.R')`


# downsampled (within+cross run)

```{r, echo = FALSE}
measure <- "down_both"
```

`r knitr::spin_child('fpc_dissoc.R')`

# downsampled, cross-run

```{r, echo = FALSE}
measure <- "down_crun"
```

`r knitr::spin_child('fpc_dissoc.R')`


# cross-validated

```{r, echo = FALSE}
measure <- "cval"
```

`r knitr::spin_child('fpc_dissoc.R')`
